### ISSUE TITLE
Lookupscreen: can't interact with lookupCancelAction button

### ISSUE THREAD

**Issue by klaus7** [mariodavid/jmix-sneferu#2]
It seems the id is missing when trying to interact with the buttons of a lookup screen.
![2022-03-30_13-59](https://user-images.githubusercontent.com/5364438/160830216-b4f2361b-6a78-4b1f-928f-85538e4a074d.png)

Part of my testing code:
```kotlin
        testAPI.getOpenedLookupScreen(CompanyBrowse::class.java).also { screen ->
            assertThat(testAPI.isActive(screen)).isTrue()
            screen.interact(click(button("lookupCancelAction"))) // <-- ERROR
        }

```

part of stacktrace:
```
Not found component with id 'lookupCancelAction'
java.lang.IllegalArgumentException: Not found component with id 'lookupCancelAction'
	at io.jmix.ui.component.HasComponents.getComponentNN(HasComponents.java:53)
	at de.diedavids.sneferu.interactions.ClickInteraction.doClick(ClickInteraction.java:27)
	at de.diedavids.sneferu.interactions.ClickInteraction.execute(ClickInteraction.java:23)
	at de.diedavids.sneferu.screen.ScreenTestAPI.doInteract(ScreenTestAPI.java:126)
	at de.diedavids.sneferu.screen.ScreenTestAPI.interact(ScreenTestAPI.java:87)
...
```

**Comment by mariodavid** [comment]
hi @klaus7,

just from the name: `lookupCancelAction` sounds more like an id of an action, not a button. Can you share the code of the lookup screen?

**Comment by klaus7** [comment]
hi @mariodavid , thanks for your fast response. you are absolutely correct, it was my mistake - that was the action of the button. I added an id and now it works. Is there a way to interact with an action?

**Comment by mariodavid** [comment]
For now it is not possible. I'm not sure if this is possible in general / without a lot of effort. 

The reason is that the action interface is not a successor of `Component`. Sneferu builds its abstractions fundamentally on the `io.jmix.ui.component.Component` interface.  I think actions also cannot be fetched via  `io.jmix.ui.component.HasComponents.getComponentNN`, but I might be wrong on that.
